const story = `
It wasn't long before the end began. Our whole world dissolved and there was nothing left but a comforting sort of peace. The endlessness of the space was less than comforting however, and despite it having the trappings of heaven, we were confidently opposed to the notion, as we were aware of what we'd done. Before it all ended, however, before this frightful notion became our woeful reality, there was a different sort of peace, in which the places we lived were saturated with moss and the poems we wrote filled our worlds with reason. It was a simpler time in a matter of speaking, but it wasn't necessarily pleasant. Before the end, before the ground split apart and we fell through the not-sky, our home was one of many and the lands we ventured were utterly unclaimed. The world had been empty and we made it full, and created little gods to maintain our control. The beasts despised our poetic nature and our fanciful tricks, and so we gave them something to worship, to let them feel a fraction of our awe. We didn't mean to give them cause to rebel. It was simply a temporary solution. It made sense at the time. Eventually, however, the beasts saw our little gods as more important than us, the little gods' creators. They mustered their little faith and stormed our many homes, took our poetry and replaced it with their own, a rambling ode to the divinity of our creations. We didn't want to fight, of course, as the beasts were bound to win, but it was hopeless. Not a scratch, but a wound was inflicted upon us, and our little gods took the throne. They didn't have the EXPERIENCE to rule, and they certainly didn't have the judgement. They were narrowly tailored, designed for our tiny tasks, and predictably they wrought pain untold upon our vast world. Deserts, suns, and moons collapsed in on themselves under their unguided power, and now we simply sit here, waiting for a door which will never arrive. The comfy chairs and wooden spoons don't fool us. This is our eternal torment.

Upon our arrival, tempers flared: How could we have lost to unpoetic beings? One of us was killed in the discussion. No hope for our revival was ever to be present. We were dead, and it was fine. We took to admiring the still white lakes and our own haunting visages. We found beauty in that clinical realm, but apparently any semblance of joy was more than we deserved. A beast joined us one day, and fury was once more our only option. It had done nothing, and yet we killed it with a cold-hearted and ancient passion. The empty and precise nature of our new home only made the corpse more disorienting. We lamented our actions but nothing could be undone. We could pretend it wasn't there at first, but we began to feel our minds dissolving and our conscience gnawing every time we saw it lying there. Our prison had lost its peculiar glimmer, and we could only sit there and ponder if THIS was guilt. We had our chance to prove ourselves. The room was not built to be eventually enjoyed, it was meant for the eternal crushing of dreams. So we sat, every day, in the presence of that disheveled reminder of our sins. Every day we lost ourselves, until there was only me. I sit here alone to atone for my misdeeds, if that is indeed what they were. The new home's clinical nature is overgrown now, but I cannot delight in those flowers knowing the forsaken land from which they grew.
`;

const probabilityMaps = new Array(4).map((_, i) => getProbabilityMap(story, i + 1));
const storyLineTerminators = new Set(".!?");

function getStorySentence(coherence) {
	const maxChars = 50 + coherence * 100;
	return generateConstrainedSentence(
		probabilityMaps[Math.min(coherence, probabilityMaps.length - 1)],
		storyLineTerminators,
		text => text.length < maxChars
	);
}